FROM node:18

WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install --ignore-scripts

RUN npm rebuild bcrypt sqlite3

# Copy code
COPY app.js .
COPY server ./server
COPY public ./public

EXPOSE 5000

CMD ["node", "app.js"]


